version: "3.8"

services:
  db:
    image: postgres:15
    container_name: db_prod
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: notas_explicativas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: app_prod
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/notas_explicativas?schema=public"
    command: sh -c "npx prisma migrate deploy && npm run start"

volumes:
  postgres_data:
